package View;


import Beans.Pessoa;
import DAO.PessoaDAO;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author laboratorio
 */
public class View2 extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(View2.class.getName());

    /**
     * Creates new form View2
     */
    public View2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_Sexo = new javax.swing.JTextField();
        btnGrp_Sexo = new javax.swing.ButtonGroup();
        txt_Idioma = new javax.swing.JTextField();
        lbl_id = new javax.swing.JLabel();
        txt_ID = new javax.swing.JTextField();
        lbl_Nome = new javax.swing.JLabel();
        txt_Nome = new javax.swing.JTextField();
        lbl_Sexo = new javax.swing.JLabel();
        lbl_Idioma = new javax.swing.JLabel();
        btn_Consultar = new javax.swing.JButton();
        btn_Att = new javax.swing.JButton();
        lbl_Id2 = new javax.swing.JLabel();
        txt_Id2 = new javax.swing.JTextField();
        tbn_Excluir = new javax.swing.JButton();
        rdo_M = new javax.swing.JRadioButton();
        rdo_F = new javax.swing.JRadioButton();
        cmb_Idioma = new javax.swing.JComboBox<>();

        txt_Idioma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_IdiomaActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lbl_id.setText("ID:");

        txt_ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_IDActionPerformed(evt);
            }
        });

        lbl_Nome.setText("Nome:");

        txt_Nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_NomeActionPerformed(evt);
            }
        });

        lbl_Sexo.setText("Sexo:");

        lbl_Idioma.setText("Idioma:");

        btn_Consultar.setText("Consultar");
        btn_Consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ConsultarActionPerformed(evt);
            }
        });

        btn_Att.setText("Atualizar");
        btn_Att.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AttActionPerformed(evt);
            }
        });

        lbl_Id2.setText("ID:");

        txt_Id2.setEnabled(false);

        tbn_Excluir.setText("Excluir");
        tbn_Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbn_ExcluirActionPerformed(evt);
            }
        });

        btnGrp_Sexo.add(rdo_M);
        rdo_M.setText("Masculino");

        btnGrp_Sexo.add(rdo_F);
        rdo_F.setText("Feminino");

        cmb_Idioma.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Português", "Espanhol", "Inglês", "Francês" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(70, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tbn_Excluir)
                        .addGap(18, 18, 18)
                        .addComponent(btn_Att))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(lbl_Sexo)
                                    .addGap(18, 18, 18)
                                    .addComponent(rdo_M)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(rdo_F))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(lbl_Nome)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txt_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lbl_id)
                                    .addGap(18, 18, 18)
                                    .addComponent(txt_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(76, 76, 76))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(lbl_Id2)
                                    .addGap(18, 18, 18)
                                    .addComponent(txt_Id2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_Idioma)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cmb_Idioma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(56, 56, 56)
                        .addComponent(btn_Consultar)))
                .addGap(126, 126, 126))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Consultar)
                    .addComponent(lbl_id))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Id2)
                    .addComponent(txt_Id2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Nome)
                    .addComponent(txt_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Sexo)
                    .addComponent(rdo_M)
                    .addComponent(rdo_F))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Idioma)
                    .addComponent(cmb_Idioma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Att)
                    .addComponent(tbn_Excluir))
                .addGap(155, 155, 155))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_IDActionPerformed

    private void txt_NomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_NomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_NomeActionPerformed

    private void btn_ConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ConsultarActionPerformed
        int idPessoa = Integer.parseInt(txt_ID.getText());
        PessoaDAO pDAO = new PessoaDAO();
        
        Pessoa p = pDAO.getPessoa(idPessoa);
        if(p == null){
            limparFormulario();
            JOptionPane.showMessageDialog(this, "Pessoa não encontrada");
        }else{
            txt_Id2.setText(p.getId()+"");
            txt_Nome.setText(p.getNome());
            //txt_Sexo.setText(p.getSexo());
            if(p.getSexo().equals("M")){
                rdo_M.setSelected(true);
            }else {
                rdo_F.setSelected(true);
            }
            //txt_Idioma.setText(p.getIdioma());
            cmb_Idioma.setSelectedItem(p.getIdioma());
        }
    }//GEN-LAST:event_btn_ConsultarActionPerformed

     private void limparFormulario(){
        txt_ID.setText("");
        txt_Id2.setText("");
        txt_Nome.setText("");
        btnGrp_Sexo.clearSelection();
        cmb_Idioma.setSelectedIndex(0);
    }
     
    private void btn_AttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AttActionPerformed
        String sexo = null;
        if(rdo_M.isSelected()){
            sexo = "M";
        }else if(rdo_F.isSelected()){
            sexo = "F";
        }
        
        
        Pessoa p = new Pessoa();
        p.setId(Integer.parseInt(txt_Id2.getText()));
        p.setNome(txt_Nome.getText());
        p.setSexo(sexo);
        p.setIdioma(cmb_Idioma.getSelectedItem().toString());
        
        PessoaDAO pDAO = new PessoaDAO();
        pDAO.editar(p);
        limparFormulario();
    }//GEN-LAST:event_btn_AttActionPerformed

    private void tbn_ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbn_ExcluirActionPerformed
        int resposta = JOptionPane.showConfirmDialog(null, "Deseja realmente excluir?", "Exclusão", JOptionPane.YES_NO_OPTION);
        
        if(resposta == JOptionPane.YES_OPTION){
            PessoaDAO pDAO = new PessoaDAO();
            pDAO.excluir(Integer.parseInt(txt_Id2.getText()));
            limparFormulario();
        }
    }//GEN-LAST:event_tbn_ExcluirActionPerformed

    private void txt_IdiomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_IdiomaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_IdiomaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new View2().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGrp_Sexo;
    private javax.swing.JButton btn_Att;
    private javax.swing.JButton btn_Consultar;
    private javax.swing.JComboBox<String> cmb_Idioma;
    private javax.swing.JLabel lbl_Id2;
    private javax.swing.JLabel lbl_Idioma;
    private javax.swing.JLabel lbl_Nome;
    private javax.swing.JLabel lbl_Sexo;
    private javax.swing.JLabel lbl_id;
    private javax.swing.JRadioButton rdo_F;
    private javax.swing.JRadioButton rdo_M;
    private javax.swing.JButton tbn_Excluir;
    private javax.swing.JTextField txt_ID;
    private javax.swing.JTextField txt_Id2;
    private javax.swing.JTextField txt_Idioma;
    private javax.swing.JTextField txt_Nome;
    private javax.swing.JTextField txt_Sexo;
    // End of variables declaration//GEN-END:variables
}
