/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication2;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author laboratorio
 */
public class RadioButton extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RadioButton.class.getName());

    /**
     * Creates new form RadioButton
     */
    public char sexo;
    public boolean tecnologia, astronomia, esportes;
    private Arquivo arquivo;
    private List<Pessoa> listaPessoas;
    private int linhaEdicao = -1;
    
    public RadioButton() {
        initComponents();
        arquivo = new Arquivo("pessoas");
        listaPessoas = arquivo.lerArquivo();
        carregarTabela();
    }
    
        private void carregarTabela() {
       
        DefaultTableModel tabela
                = (DefaultTableModel) tbl_Pessoas.getModel();
        
        tabela.setRowCount(0);
        
        for (Pessoa p : listaPessoas) {
            tabela.addRow(p.obterDados());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrp_Sexo = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaPessoas = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txt_Nome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        rdo_Masculino = new javax.swing.JRadioButton();
        rdo_Feminino = new javax.swing.JRadioButton();
        btnSalvar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        chk_Tecnologia = new javax.swing.JCheckBox();
        chk_Astronomia = new javax.swing.JCheckBox();
        chk_Esportes = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        cmb_Idioma = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_Pessoas = new javax.swing.JTable();
        btnExcluir = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();

        txaPessoas.setColumns(20);
        txaPessoas.setRows(5);
        jScrollPane1.setViewportView(txaPessoas);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nome:");

        txt_Nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_NomeActionPerformed(evt);
            }
        });

        jLabel2.setText("Sexo:");

        btnGrp_Sexo.add(rdo_Masculino);
        rdo_Masculino.setText("Masculino");

        btnGrp_Sexo.add(rdo_Feminino);
        rdo_Feminino.setText("Feminino");

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        jLabel3.setText("Interesses:");

        chk_Tecnologia.setText("Tecnologia");

        chk_Astronomia.setText("Astronomia");

        chk_Esportes.setText("Esportes");

        jLabel4.setText("Idioma:");

        cmb_Idioma.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Espanhol", "Inglês", "Português" }));

        tbl_Pessoas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Sexo", "Idioma"
            }
        ));
        jScrollPane3.setViewportView(tbl_Pessoas);

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addComponent(txt_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmb_Idioma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(chk_Tecnologia)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(chk_Astronomia)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(chk_Esportes)))
                        .addContainerGap(188, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(rdo_Masculino)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rdo_Feminino))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnEditar)
                .addGap(18, 18, 18)
                .addComponent(btnExcluir)
                .addGap(18, 18, 18)
                .addComponent(btnSalvar)
                .addGap(130, 130, 130))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rdo_Masculino)
                        .addComponent(rdo_Feminino)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(chk_Tecnologia)
                    .addComponent(chk_Astronomia)
                    .addComponent(chk_Esportes))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmb_Idioma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExcluir)
                    .addComponent(btnEditar)
                    .addComponent(btnSalvar))
                .addGap(79, 79, 79))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed

        
        tecnologia = chk_Tecnologia.isSelected();
        
        astronomia = chk_Astronomia.isSelected();
        
        esportes = chk_Esportes.isSelected();
        
       
        
        JOptionPane.showMessageDialog(null,"Tecnologia: "+tecnologia+
                "\nAstronomia: "+astronomia+
                "\nEsportes: "+esportes, "Alerta", JOptionPane.INFORMATION_MESSAGE);
        
        if(rdo_Masculino.isSelected()){
            sexo = 'M';
            JOptionPane.showMessageDialog(null, "Sexo maculino selecionado", "Alerta", JOptionPane.OK_OPTION);
            
            //txaPessoas.append(p+"");
        }
        else if(rdo_Feminino.isSelected()){
            sexo = 'F';
            JOptionPane.showMessageDialog(null, "Sexo feminino selecionado", "Alerta", JOptionPane.OK_OPTION);
            
            //txaPessoas.append(p+"");
        }
        else{
            JOptionPane.showMessageDialog(null, "Selecione um sexo", "Erro", JOptionPane.ERROR_MESSAGE);
        }
        
        String idioma = cmb_Idioma.getSelectedItem()+"";
        
        Pessoa p = new Pessoa(txt_Nome.getText(), sexo, idioma);
        
        if(linhaEdicao == -1) {
            listaPessoas.add(p);
        }
        else{
            listaPessoas.set(linhaEdicao, p);
            linhaEdicao = -1;
        }
        arquivo.gravaArquivo();
        carregarTabela();
        JOptionPane.showMessageDialog(null, "Dados salvos com sucesso!");
        
        

        
        txt_Nome.setText("");
        btnGrp_Sexo.clearSelection();
        chk_Tecnologia.setSelected(false);
        chk_Astronomia.setSelected(false);
        chk_Esportes.setSelected(false);
        cmb_Idioma.setSelectedIndex(0);
        
        //listaPessoas.add(p);
        
        //arquivo.gravaArquivo();
        
        System.out.println("Pessoa adicionada!");
        for (Pessoa pessoa : listaPessoas) {
            System.out.println(pessoa);
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        int linha = tbl_Pessoas.getSelectedRow();
        if(linha==-1) {
            JOptionPane.showMessageDialog(null, "Selecione uma pessoa na tabela", "Atenção", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        int resposta = JOptionPane.showConfirmDialog(null, "Deseja realmente excluir esta pessoa?", "Confirmação", JOptionPane.YES_NO_OPTION);
        
        if(resposta == JOptionPane.YES_OPTION) {
            
            listaPessoas.remove(linha);
            
            arquivo.gravaArquivo();
            
            DefaultTableModel tabela
                    = (DefaultTableModel) tbl_Pessoas.getModel();
            
            tabela.removeRow(linha);
            
            System.out.println("Pessoa excluída!");
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void txt_NomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_NomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_NomeActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        int linha = tbl_Pessoas.getSelectedRow();
        System.out.println(linha);
        if(linha == -1) {
            JOptionPane.showMessageDialog(null, "Selecione uma pessoa para editar.");
            return;
        }
        linhaEdicao = linha;
        Pessoa p = listaPessoas.get(linha);
        txt_Nome.setText(p.nome);
        
        if(p.sexo == 'M'){
            rdo_Masculino.setSelected(true);
        }else {
            cmb_Idioma.setSelectedItem(p.idioma);
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new RadioButton().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.ButtonGroup btnGrp_Sexo;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JCheckBox chk_Astronomia;
    private javax.swing.JCheckBox chk_Esportes;
    private javax.swing.JCheckBox chk_Tecnologia;
    private javax.swing.JComboBox<String> cmb_Idioma;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JRadioButton rdo_Feminino;
    private javax.swing.JRadioButton rdo_Masculino;
    private javax.swing.JTable tbl_Pessoas;
    private javax.swing.JTextArea txaPessoas;
    private javax.swing.JTextField txt_Nome;
    // End of variables declaration//GEN-END:variables

}
