/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cadastrolivros;


import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author laboratorio
 */
public class TelaCadastroLivros extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaCadastroLivros.class.getName());

   // private final ArrayList<CadastroLivros> livros = new ArrayList<>();
    public char tipo;
    public char situacaoLeitura;
    private Arquivo arquivo;
    private List<CadastroLivros> listaLivros;
    private int linhaEdicao = -1;
    /**
     * Creates new form TelaCadastroLivros
     */
    public TelaCadastroLivros() {
        initComponents();
        arquivo = new Arquivo("Livros");
        listaLivros = arquivo.lerArquivo();
        carregarTabela();
    }
    
        private void carregarTabela() {
       
        DefaultTableModel tabela
                = (DefaultTableModel) tblLivros.getModel();
        
        tabela.setRowCount(0);
        
        for (CadastroLivros p : listaLivros) {
            tabela.addRow(p.obterDados());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        btnGrpTipo = new javax.swing.ButtonGroup();
        btnGrpSituacaoLeitura = new javax.swing.ButtonGroup();
        txtTitulo = new javax.swing.JTextField();
        txtAutor = new javax.swing.JTextField();
        txtAnoPublicacao = new javax.swing.JTextField();
        cmbCategorias = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLivros = new javax.swing.JTable();
        btnSalvar = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();
        lblAutor = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblSituacaoLeitura = new javax.swing.JLabel();
        lblCategorias = new javax.swing.JLabel();
        rdoFisico = new javax.swing.JRadioButton();
        lblTipo = new javax.swing.JLabel();
        rdoDigital = new javax.swing.JRadioButton();
        rdoNaoIniciado = new javax.swing.JRadioButton();
        rdoEmAndamento = new javax.swing.JRadioButton();
        rdoConcluido = new javax.swing.JRadioButton();
        btnEditar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAutorActionPerformed(evt);
            }
        });

        cmbCategorias.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tecnologia", "Ficção", "Romance", "História" }));

        tblLivros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Titulo", "Autor", "Tipo", "Categorias", "Ano de publicação", "Situação de leitura"
            }
        ));
        jScrollPane1.setViewportView(tblLivros);

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        lblTitulo.setText("Título:");

        lblAutor.setText("Autor:");

        jLabel3.setText("Ano de Publicação:");

        lblSituacaoLeitura.setText("Situação de leitura:");

        lblCategorias.setText("Categorias:");

        rdoFisico.setText("Físico");
        rdoFisico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoFisicoActionPerformed(evt);
            }
        });

        lblTipo.setText("Tipo:");

        rdoDigital.setText("Digital");

        rdoNaoIniciado.setText("Não iniciado");

        rdoEmAndamento.setText("Em Andamento");

        rdoConcluido.setText("Concluído");

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitulo)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAutor)
                            .addComponent(jLabel3)
                            .addComponent(lblCategorias))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                            .addComponent(txtAutor)
                            .addComponent(txtAnoPublicacao))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTipo)
                        .addGap(18, 18, 18)
                        .addComponent(rdoFisico)
                        .addGap(18, 18, 18)
                        .addComponent(rdoDigital)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblSituacaoLeitura)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rdoEmAndamento)
                            .addComponent(rdoNaoIniciado)
                            .addComponent(rdoConcluido))
                        .addGap(84, 84, 84))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addGap(42, 42, 42))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEditar)
                .addGap(50, 50, 50)
                .addComponent(btnSalvar)
                .addGap(154, 154, 154))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTitulo)
                    .addComponent(lblTipo)
                    .addComponent(rdoFisico, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rdoDigital))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAutor)
                    .addComponent(lblSituacaoLeitura)
                    .addComponent(rdoNaoIniciado))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAnoPublicacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCategorias)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rdoEmAndamento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rdoConcluido)))
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditar)
                    .addComponent(btnSalvar))
                .addContainerGap(98, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void txtAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAutorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAutorActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        if(rdoFisico.isSelected()){
            tipo = 'F';
            JOptionPane.showMessageDialog(null, "Tipo fisico selecionado", "Alerta", JOptionPane.OK_OPTION);
            
             
        }
        else if(rdoDigital.isSelected()){
            tipo = 'D';
            JOptionPane.showMessageDialog(null, "Tipo digital selecionado", "Alerta", JOptionPane.OK_OPTION);
            
             
        }
        else{
            JOptionPane.showMessageDialog(null, "Selecione um tipo de livro: ", "Erro", JOptionPane.ERROR_MESSAGE);
        }
        
        
        if(rdoNaoIniciado.isSelected()){
            tipo = 'N';
            JOptionPane.showMessageDialog(null, "Situação Leitura: não iniciada selecionada", "Alerta", JOptionPane.OK_OPTION);
            
             
        }
        else if(rdoEmAndamento.isSelected()){
            tipo = 'E';
            JOptionPane.showMessageDialog(null, "Situação Leitura: em andamento selecionado", "Alerta", JOptionPane.OK_OPTION);
            
             
        }
        else if(rdoConcluido.isSelected()){
            tipo = 'C';
            JOptionPane.showMessageDialog(null, "Situação Leitura: concluído selecionado", "Alerta", JOptionPane.OK_OPTION);
            
             
        }
        else{
            JOptionPane.showMessageDialog(null, "Selecione um tipo de livro: ", "Erro", JOptionPane.ERROR_MESSAGE);
        }
        
        String categorias = cmbCategorias.getSelectedItem()+"";
        
        CadastroLivros l = new CadastroLivros(txtTitulo.getText(), txtAutor.getText(), categorias, txtAnoPublicacao.getText(), tipo, situacaoLeitura);
        
        if(linhaEdicao == -1) {
            listaLivros.add(l);
        }
        else{
            listaLivros.set(linhaEdicao, l);
            linhaEdicao = -1;
        }
        arquivo.gravaArquivo();
        carregarTabela();
        JOptionPane.showMessageDialog(null, "Dados salvos com sucesso!");
        
        

        
        txtTitulo.setText("");
        txtAutor.setText("");
        txtAnoPublicacao.setText("");
        btnGrpTipo.clearSelection();
        btnGrpSituacaoLeitura.clearSelection();
        cmbCategorias.setSelectedIndex(0);
        
         
        
        System.out.println("Pessoa adicionada!");
        for (CadastroLivros livro : listaLivros) {
            System.out.println(livro);
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void rdoFisicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoFisicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdoFisicoActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        int linha = tblLivros.getSelectedRow();
        System.out.println(linha);
        if(linha == -1) {
            JOptionPane.showMessageDialog(null, "Selecione um livro para editar.");
            return;
        }
        linhaEdicao = linha;
        CadastroLivros l = listaLivros.get(linha);
        txtTitulo.setText(l.titulo);
        txtAutor.setText(l.autor);
        txtAnoPublicacao.setText(l.anoPublicacao);
        
        if(l.tipo == 'F'){
            rdoFisico.setSelected(true);
        }
        else if(l.situacaoLeitura == 'N'){
            rdoNaoIniciado.setSelected(true);
        }
        else {
            cmbCategorias.setSelectedItem(l.categorias);
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaCadastroLivros().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.ButtonGroup btnGrpSituacaoLeitura;
    private javax.swing.ButtonGroup btnGrpTipo;
    private javax.swing.JButton btnSalvar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.JComboBox<String> cmbCategorias;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAutor;
    private javax.swing.JLabel lblCategorias;
    private javax.swing.JLabel lblSituacaoLeitura;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JRadioButton rdoConcluido;
    private javax.swing.JRadioButton rdoDigital;
    private javax.swing.JRadioButton rdoEmAndamento;
    private javax.swing.JRadioButton rdoFisico;
    private javax.swing.JRadioButton rdoNaoIniciado;
    private javax.swing.JTable tblLivros;
    private javax.swing.JTextField txtAnoPublicacao;
    private javax.swing.JTextField txtAutor;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
